services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: suumo
      TZ: Asia/Tokyo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodb/data:/data/db\

  scraper:
    build:
      context: ./scraper
      dockerfile: ./docker/Dockerfile
    image: suumo-scraper
    container_name: suumo-scraper
    restart: "no"
    environment:
      TZ: Asia/Tokyo
      MONGO_URI: mongodb://admin:password@mongodb:27017/?authSource=admin
      MONGO_DB_NAME: suumo
      MONGO_COLLECTION_NAME: listings
      MONGO_COLLECTION_DETAILS: details
      MONGO_COLLECTION_STATE: scraper_state
      SCRAPE_MODE: DETAILS  # LISTING or DETAILS
    depends_on:
      - mongodb
